/**
 * My API
 * This is a description of my API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HttpHeadersHostAddress { 
    canonicalHostName?: string;
    hostAddress?: string;
    address?: Array<string>;
    hostName?: string;
    linkLocalAddress?: boolean;
    anyLocalAddress?: boolean;
    multicastAddress?: boolean;
    loopbackAddress?: boolean;
    siteLocalAddress?: boolean;
    mcglobal?: boolean;
    mcnodeLocal?: boolean;
    mclinkLocal?: boolean;
    mcsiteLocal?: boolean;
    mcorgLocal?: boolean;
}

