/**
 * Your API Title
 * Description of your API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HttpHeadersAcceptLanguageAsLocalesInner { 
    language?: string;
    displayName?: string;
    country?: string;
    variant?: string;
    script?: string;
    unicodeLocaleAttributes?: Set<string>;
    unicodeLocaleKeys?: Set<string>;
    displayLanguage?: string;
    displayScript?: string;
    displayCountry?: string;
    displayVariant?: string;
    extensionKeys?: Set<string>;
    iso3Language?: string;
    iso3Country?: string;
}

