/**
 * My API
 * This is a description of my API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContentDisposition } from './contentDisposition';
import { HttpHeadersHost } from './httpHeadersHost';
import { ContentDispositionCharset } from './contentDispositionCharset';
import { MediaType } from './mediaType';
import { HttpHeadersAcceptLanguageAsLocalesInner } from './httpHeadersAcceptLanguageAsLocalesInner';
import { HttpHeadersAcceptLanguageInner } from './httpHeadersAcceptLanguageInner';


export interface HttpHeaders { 
  [key: string]: Array<string> | any;


    empty?: boolean;
    location?: string;
    host?: HttpHeadersHost;
    all?: { [key: string]: string; };
    lastModified?: number;
    date?: number;
    contentLength?: number;
    accessControlAllowCredentials?: boolean;
    accessControlAllowHeaders?: Array<string>;
    accessControlAllowMethods?: Array<object>;
    accessControlAllowOrigin?: string;
    accessControlExposeHeaders?: Array<string>;
    accessControlRequestHeaders?: Array<string>;
    accessControlRequestMethod?: object;
    connection?: Array<string>;
    acceptLanguageAsLocales?: Array<HttpHeadersAcceptLanguageAsLocalesInner>;
    acceptPatch?: Array<MediaType>;
    accessControlMaxAge?: number;
    acceptCharset?: Array<ContentDispositionCharset>;
    bearerAuth?: string;
    cacheControl?: string;
    contentDisposition?: ContentDisposition;
    contentLanguage?: HttpHeadersAcceptLanguageAsLocalesInner;
    ifNoneMatch?: Array<string>;
    ifUnmodifiedSince?: number;
    acceptLanguage?: Array<HttpHeadersAcceptLanguageInner>;
    basicAuth?: string;
    range?: Array<object>;
    origin?: string;
    accept?: Array<MediaType>;
    allow?: Set<object>;
    etag?: string;
    expires?: number;
    ifMatch?: Array<string>;
    pragma?: string;
    upgrade?: string;
    vary?: Array<string>;
    contentType?: MediaType;
    ifModifiedSince?: number;
}

