/**
 * Your API Title
 * Description of your API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpStatusCode } from './httpStatusCode';
import { ResponseEntityVoidHeaders } from './responseEntityVoidHeaders';


export interface ResponseEntityVoid { 
    headers?: ResponseEntityVoidHeaders;
    body?: object;
    statusCodeValue?: number;
    statusCode?: HttpStatusCode;
}

